<?php

use Illuminate\Database\Seeder;
use App\IntelligenceIndicator;

class IntelligenceIndicatorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $indicators_array = ['le gusta jugar con los otros compañeros.', 
                            'disfruta de la convivencia con los demás.', 
                            'tiene un buen sentido de la empatía y del interés por  los otros. los compañeros buscan su compañía.', 
                            'pertenece a clubes, comités y otras organizaciones parecidas. tiene dos o más amigos íntimos.',
                            'parece ser un líder natural. aconseja a los iguales que tienen problemas.',
                            'parece comportarse muy inteligentemente en la calle.',
                            'disfruta de enseñar informalmente a otros.  aconseja a los iguales que tienen problemas.',
                            'le interesa conocer sobre los grupos de personas y las comunidades.',
                            'lidera planes colectivos.', 
                            'logra comprender las intenciones de las otras personas.',
                            'se interesa por las actividades sociales y ambientales.',
                            'se preocupa por los demás.',
                            'manifiesta gran fuerza de voluntad y capacidad para automotivarse.',
                            'tiene un buen sentido de la auto-dirección.',
                            'prefiere trabajar sólo a trabajar con otros. manifiesta gran sentido de la independencia.',
                            'expresa con precisión cómo se siente.',
                            'tiene un sentido realista de sus fuerzas y debilidades.',
                            'puede pensar planes según las circunstancias. puede trabajar solo.',
                            'cuando cree que algo vale la pena, se esfuerza al cien por cien.',
                            'le gusta manifestar cómo se siente y sus estados de ánimo.',
                            'disfruta corriendo, saltando, o realizando actividades semejantes. le gusta el deporte.',
                            'mueve, golpea o lleva el ritmo cuando está sentado en un lugar.',
                            'tiene una manera dramática de expresarse.',
                            'disfruta trabajando con experiencias táctiles.',
                            'informa de diferentes sensaciones físicas mientras piensa o trabaja.',
                            'le gusta el movimiento y las relaciones espaciales, es propositivo.',
                            'le gustan los deportes y los juegos al aire libre. vive un estilo de vida activo.',
                            'vincula las actividades diarias con movimiento y deporte.',
                            'compara, valora, resume y saca conclusiones con facilidad. disfruta con los juegos de palabras. disfruta con los juegos de lectura. aprecia rimas sin sentido, juegos de palabras… disfruta al escuchar.',
                            'tiene buena memoria para nombres, plazos, fechas.',
                            'pronuncia las palabras de forma precisa (por encima de la media). disfruta con los juegos de palabras.',
                            'aprecia rimas sin sentido, juegos de palabras.',
                            'se comunica con otros de manera verbal en un nivel alto.',
                            'cuenta historias, relatos, cuentos y chistes con precisión.',
                            'escribe mejor que el promedio de su edad. cuenta historias, relatos, cuentos y chistes con precisión.',
                            'deduce información sobre datos, discursos y aclaraciones.',
                            'disfruta de la poesía y las figuras literarias.',
                            'disfruta relatos, historias y se interesa por narrarlos.',
                            'le resulta fácil explicar sus ideas a otros.',
                            'me gusta jugar con palabras como los anagramas, las palabras encadenadas. tengo buena memoria para los lugares, fechas, nombres.  me gusta comunicarme con mis amigos a través de cartas, e-mails o mensajes. me gusta leer toda clase de cosas.',
                            'posee grandes habilidades de memoria auditiva.',
                            'se basa en la experiencia de los otros y busca red de apoyo en momentos de requerir ayuda.',
                            'tiene habilidades frente a la noción de temporalidad resuelve rápidamente problemas aritméticos en su cabeza. disfruta de las clases de matemáticas. encuentra interesante los juegos matemáticos. disfruta trabajando en puzzles lógicos. le gusta trabajar en tareas que revelan claramente  procesos superiores',
                            'muestra facilidad para localizar el tiempo,tiene habilidades frente a la noción de temporalidad.',
                            'disfruta jugando al ajedrez u otros juegos de estrategia.',
                            'categoriza o establece jerarquías.',
                            'tiene habilidades para el cálculo operativo, encuentra interesante los juegos matemáticos. disfruta trabajando en puzzles lógicos.',
                            'disfruta categorizando o estableciendo jerarquías.',
                            'juegos de estrategia',
                            'disfruta categorizando o estableciendo jerarquías. logra realizar inferencias a partir de datos. disfruta de juegos operativos y puzzles lógicos.',
                            'disfruta con las actividades de pensamiento o  estrategia.',
                            'logra recordar datos cuando estos son organizados en un orden preestablecido.',
                            'me gusta trabajar con las hojas de cálculo o las bases de datos del ordenador.',
                            'pone en juego la estrategia para la resolución de problemas.',
                            'pone todo en orden para tener éxito en las actividades.',
                            'puede realizar cálculos mentales rápidamente. resuelve problemas de manera fácil. los puzzles que requieren razonamiento la parecen divertidos. las instrucciones paso a paso le son de gran ayuda. pone todo en orden para tener éxito en las actividades. le gusta trabajar con  hojas de cálculo o bases de datos. utilizo un orden lógico en los planes que realizo.',
                            'puedo realizar cálculos operativos.',
                            'resolver problemas es fácil para mí. puedo realizar cálculos mentales rápidamente. me gusta trabajar con las hojas de cálculo o las bases de datos del ordenador.',
                            'se comunica a través de datos numéricos.',
                            'tiene un pensamiento lógico y estratégico.',
                            'canta canciones aprendidas fuera del colegio.',
                            'recuerda con facilidad melodías y canciones. tararea para sí mismo de forma inconsciente. responde favorablemente cuando suena una melodía musical.',
                            'tiene facilidad para identificar sonidos diferentes y percibir matices, se expresa con sonidos.',
                            'es sensible a los ruidos ambientales. tiene buena discriminación auditiva. responde favorablemente cuando suena una melodía musical.',
                            'reconocimiento de patrones sonoros, tiene facilidad para identificar sonidos diferentes y percibir matices.',
                            'golpetea rítmicamente sobre la mesa o pupitre mientras trabaja.',
                            'asociación de sonidos con situaciones o emociones,  golpetea rítmicamente sobre la mesa o pupitre mientras trabaja.',
                            'se interesa por  canciones de diversas temáticas.',
                            'le interesa el estudio de la música y su componente en la comunidad.',
                            'puede reconocer patrones musicales y disfruta de su análisis.',
                            'recuerdo las cosas poniéndoles un ritmo.',
                            'tiene facilidad para emitir sonidos diferentes, se expresa con sonidos.',
                            'le gusta relatar situaciones de la naturaleza  es curioso, le gusta formular preguntas y busca información adicional sobre la naturaleza. le gusta manipular materiales novedosos en el aula y fuera de ella.  puede comprender el comportamiento animal o ciclos naturales.',
                            'disfruta con las clases de conocimiento del medio.',
                            'se interesa por los conocimientos de la naturaleza.',
                            'compara y clasifica objetos, materiales y cosas atendiendo a sus propiedades físicas y materiales. posee un gran conocimiento sobre temas relacionados con las ciencias naturales.',
                            'suele predecir el resultado de las experiencias antes de realizarlas. tiene buenas habilidades a la hora de establecer relaciones causa-efecto.',
                            'creo que preservar nuestros parques naturales es importante.',
                            'el senderismo y el camping le divierten.',
                            'le da un orden lógico o jerarquiza los datos.',
                            'le gusta relatar situaciones de la naturaleza,  puede comprender el comportamiento animal o ciclos naturales.',
                            'le interesan los datos científicos y de orden natural.',
                            'relata situaciones de la naturaleza, organiza los datos de un suceso natural.',
                            'muestra facilidad para localizar en el espacio, imaginar movimientos, etc.',
                            'tiene desarrollo de las habilidades percepción visoespacial.',
                            'construye imágenes en su mente.',
                            'desarrollo lateral, sentido espacial.',
                            'muestra facilidad para localizar el tiempo.',
                            'informa de imágenes visuales claras.',
                            'disfruta de las actividades artísticas.',
                            'asocia de manera fácil la información visual.',
                            'frecuentemente toca lo que ve o escucha.',
                            'puede deducir ideas a nivel visual.',
                            'le atraen las actividades visuales, donde se deban detallar colores y formas.',
                            'me resulta fácil comprender e interpretar y leer mapas, diagramas, gráficos y tablas.',
                            'organiza de manera espacial la información en su mente.',
                            'organiza, conceptualiza y deduce información de manea visoespacial a través de mapas mentales u organizadores gráficos.',
                            'puede visualizar o imaginar datos sobre información recibida.',
                            'se apoya de imágenes para la comprensión parcial o total de la idea.',
                            'se involucra con las razones sociales y reconoce las luchas populares.',
                            'reconoce la emociones y sus expresiones.',
                            'reconoce sus sentimientos frente a simbología popular o ancestral.',
                            'se traza objetivos y realiza planes para lograrlos.',
                            'muestra habilidad en la coordinación viso-motora.',
                            'imita inteligentemente los gestos o posturas de otras personas.',
                            'muestra habilidad en la coordinación viso-motora. realiza dibujos interesantes  para su edad, puede imitar trazos. puede deducir ideas a nivel visual.',
                            'imita inteligentemente los gestos o posturas de otras personas. muestra habilidad en la coordinación viso-motora.',
                            'tiene amplia habilidad motora para el trabajo artesanal y el detalle manual.',
                            'se interesa por la producción de figuras literarias.',
                            'escribe mejor que el promedio de su edad.',
                            'cuenta historias, relatos, cuentos y chistes con precisión.',
                            'realiza narraciones de mitos, leyendas, cuentos, chistes.',
                            'resuelve rápidamente problemas aritméticos en su cabeza, resuelve puzzles matemáticos.',
                            'opera con medidas, longitudes y cantidades.',
                            'asociación de sonidos con situaciones o emociones.',
                            'es hábil en la contrucción de canciones y memoría auditiva.',
                            'se interesa por la construcción de instrumentos y elementos sonoros.',
                            'le gusta relatar situaciones de la naturaleza,  puede comprender el comportamiento animal o ciclos naturales.',
                            'suele predecir el resultado de las experiencias antes de realizarlas.   tiene buenas habilidades a la hora de establecer relaciones causa-efecto.',
                            'se interesa por los animales y los elementos de la naturaleza.',
                            'le gusta relatar situaciones de la naturaleza,  puede comprender el comportamiento animal o ciclos naturales.',
                            'se siente inspirado o atraído por temas de la naturaleza.',
                            'logra transformar imagenes o visualizaciones en ideas o datos concretos.',
                            'puede realizar copiado de trazos, gráficos, dibujos buenos para su edad, se interesa por los gráficos.',
                            'le gusta mover las cosas y cambiarlas frecuentemente.',
                            'le impactan las reacciones visuales, los colores y las demostraciones de formas.',
                            'le gusta mover las cosas y cambiarlas frecuentemente.  disfruta actividades artísticas.',
                            'realiza contenido en 2d y 3d, intersante para su edad. puede imitar trazos. puede deducir ideas a nivel visual.',
                            'le gusta mover las cosas y cambiarlas frecuentemente.',
                            'realiza dibujos interesantes  para su edad, puede imitar trazos. puede deducir ideas a nivel visual.'
                        ];

        $intelligences_array = [300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300,
                                301, 301, 301, 301, 301, 301, 301, 301,
                                302, 302, 302, 302, 302, 302, 302, 302,
                                303, 303, 303, 303, 303, 303, 303, 303, 303, 303, 303, 303, 303, 303,
                                304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304,
                                305, 305, 305, 305, 305, 305, 305, 305, 305, 305, 305, 305,
                                306, 306, 306, 306, 306, 306, 306, 306, 306, 306, 306,
                                307, 307, 307, 307, 307, 307, 307, 307, 307, 307, 307, 307, 307, 307, 307, 307,
                                301, 301, 301, 301, 
                                302, 302, 302, 302, 302, 
                                303, 303, 303, 303, 
                                304, 304, 
                                305, 305, 305,
                                306, 306, 306, 306, 306,
                                307, 307, 307, 307, 307, 307, 307, 307];
        
        foreach ($indicators_array as $key => $element) {
            $new_intelligence_indicator = new IntelligenceIndicator();
            $new_intelligence_indicator->description = $element;
            $new_intelligence_indicator->intelligence_id = $intelligences_array[$key];
            $new_intelligence_indicator->save();
        }
    }
}
